### ISSUE TITLE
Timer value lost in flows after update

### ISSUE THREAD

**Issue by cbho** [ralfvd/nl.bevlogenheid.countdown#12]
Homey FW 1.5.8
App 1.2.3

Problem:
With reference to the flow shown below:
The flow works fine, have not made any changes for a long time and don't need to do - by coincidence I clicked on it in Homey app - and...

![image](https://user-images.githubusercontent.com/29979509/37531799-82215886-293d-11e8-9aeb-3768ec4da71e.png)

The value field in the flow card "Start countdown timer" is empty...
If using "Test" in Homey app, the flow cannot be triggered, neither can the flow be saved, if no new value 
is entered.

However, as the flow can be triggered from another show, it is quite easy to check if it works - which it actually do!
Triggering the flow sets the timer and count down is initiated:
![image](https://user-images.githubusercontent.com/29979509/37532214-ab33dab8-293e-11e8-8447-c1431e53ae1a.png)

So, somehow values are saved, but not saved at the same time - as long as the flow is not changed, the value is left and stuff will work - if you change anything in the flow and have to save it, it is also necessary to input a value in the field anew (Schrödingers countdown flowcard ;-))

As flows are working as long as they are left untouched, it is not a major problem, especially if you remember which value was the optimum - but still a bug :-)

**Comment by bvdbos** [comment]
Do the flows keep working after a reboot? I suspect saving the variables is an issue, keeping in memory is not?

**Comment by canedje** [comment]
I had the same.
I reentered all values again, now it is working

**Comment by cbho** [comment]
Flows work fine after reboot - also if no value is entered.
Values re-entered yesterday at the time of making the issue are saved.

**Comment by Povlov** [comment]
As I would expect, when a timer value is set within a flow, as cbho mentions.
In flows such as this one, I need to re-enter the values manually.
![screenshot 2018-03-17 at 11 39 03](https://user-images.githubusercontent.com/24312420/37554405-2afaa3aa-29d8-11e8-9d8e-652a009bdcc7.png)

**Comment by ralfvd** [comment]
I found the issue, but not sure why this is happening; I changed the timer value input to 'number' instead of text, as I suspected some app crashes were caused by non-numeric input. 

But somehow, although the variable type is reported 'number' by Node.Js, it doesn't display in a flowcard, unless you save the value again.  

I will update the app with the value input back to text, and investigate further why this is happening.

Sorry I didn't catch this myself before publishing the app.

**Comment by Povlov** [comment]
No problem! It is a great app, your effort is appreciated!

**Comment by ralfvd** [comment]
@Povlov  in settings, all timers are always to '-1' when they are not running. You won't see the values entered your flows there. There is an app to backup flows, so you might be able to use that to store your 'perfect' values: https://apps.athom.com/app/nl.regoor.flowbackup

Version 1.2.4 which reverts the input validation is now published in the app store. I'll keep the issue open to fix the input validation, without causing flows to lose their values.
