### ISSUE TITLE
SDK2

### ISSUE THREAD

**Issue by WrDX** [ralfvd/nl.bevlogenheid.countdown#13]
In the (hopefully) near future Athom will release Homey V2. Is it possible that you update your app to SDK2? When V2 is released all setting pages for SDK1 apps won't work anymore.

**Comment by ralfvd** [comment]
Hi, this coming weeks/months I will start the rewrite to SDK-2.

**Comment by PatrickSannes** [comment]
Hi Ralf, not sure if you are using slack anymore. I just started rewriting better logic to sdk2. Can you join me there for some discussion?

**Comment by ralfvd** [comment]
SDK2 is now pending approval in the app store. You can install from GitHub if you want earlier access. Please let me know if there are any issues!
