### ISSUE TITLE
after update countdown does not trigger my flows anymore

### ISSUE THREAD

**Issue by glijie** [ralfvd/nl.bevlogenheid.countdown#18]
After update to version v2.0.0 - 07.12.18 the card under does not trigger my flows anymore.
Homey Firmware Versie: 1.5.13

![countdown](https://user-images.githubusercontent.com/19786633/49665546-837d6f00-fa55-11e8-8455-52900033964f.JPG)

**Comment by ralfvd** [comment]
2.0.1 has just been released in the app store, that should solve this issue. thanks for noticing!

**Comment by ralfvd** [comment]
Oops, my use case didn't catch that. Code was not cleaned finding the issue that I fixed, which now caused a double trigger instead of one.  Many use cases won't see the difference, that's why I didn't catch it in my testing.

2.0.2 is now pending approval in the app store. Thanks!

**Comment by glijie** [comment]
thx, bought you some beer for the weekend.

**Comment by ralfvd** [comment]
Much appreciated!
