### ISSUE TITLE
fault rc2 or countdown

### ISSUE THREAD

**Issue by satbopper** [ralfvd/nl.bevlogenheid.countdown#20]
Do not know if it is the 2.0 rc2 version or countdown itself but i have a flow
containing if zandloper leeg  met de juiste naam van de timer and i try to save the flow i get the message 
er ging iets fout probeer het later opnieuw could not find that flowcard action
countdown is 2.0.1

**Comment by satbopper** [comment]
idem for 2.0.2

**Comment by ralfvd** [comment]
Is this an existing flow or a new flow?  What happens if you re-enter the timer name in the 'if zandloper leeg' card? Do you see the 'autocompletion' list?

**Comment by ralfvd** [comment]
Closing this one as it was created a long time ago, and no more input was retrieved from the originator.
