### ISSUE TITLE
Timer value lost in flows after update

### ISSUE THREAD

**Issue by GPBruins** [ralfvd/nl.bevlogenheid.countdown#22]
Dear Ralf,

The timer values are lost in the flows since the last update. However, Homey still knows them, they work correct.

Yours,

Guus Bruins

![overloop countdown](https://user-images.githubusercontent.com/35421350/49697113-c0f80e80-fbb3-11e8-89b8-7964505efeee.jpg)

**Comment by ralfvd** [comment]
This should be fixed in 2.0.3 which has just been released in the app store. let me know if there are still issues.

**Comment by GPBruins** [comment]
Dear Ralf,

Flawless as it used to be. Thanks for the swift response.

Guus Bruins
