### ISSUE TITLE
Feature request: Random Time

### ISSUE THREAD

**Issue by dirkg173** [ralfvd/nl.bevlogenheid.countdown#33]
Is it possible to add simple mathematical calculations to calculate a random time?
In the Chronograph App by Bob Kersten it is possible. But the app seems to be no longer developed or maintained.
![IMG_1048](https://user-images.githubusercontent.com/40319629/91036007-d66ecf80-e606-11ea-9401-b51c26956b98.PNG)

**Comment by ralfvd** [comment]
An action with a random timer has been added a while ago, so this issue will be closed. Thanks for the idea!
