### ISSUE TITLE
App won't  trigger a flow every time a timer is started/updated. 

### ISSUE THREAD

**Issue by tranceblast** [ralfvd/nl.bevlogenheid.countdown#34]
App won't  trigger a flow every time a timer is started/updated. 

I tried to have a flow like this:
When: timer start/update
Then: turn on light

This only work if the timer not running.
I have tested the app chronograph, and on this app it works.

**Comment by ralfvd** [comment]
Hi,

sorry for the delay. Indeed, the timer start-card is only triggered when the flow is started from a 'stopped' position. 

For the new 2.0.5 release I have now added two extra action cards:

- Updated ; so this triggers when a flow is running and the timer is updated manually or via a flow
- Started/updated; this triggers when a timer is either updated or started.

The 2.0.5 release is now under review by Athom, so hopefully available in a couple of days. 

Thanks for your patience and thanks for the suggestion!
