### ISSUE TITLE
NL localization

### ISSUE THREAD

**Issue by BOverdevest** [ralfvd/nl.bevlogenheid.countdown#35]
Hi. Great app. 
Two Dutch language improvement proposal
1) draai zandloper om --> start zandloper
2) stop countdown timer --> stop zandloper

Also, on the app info page you mentioned there are three actions for flows, while there 5 mentioned. 

Keep it up!
Bart

**Comment by ralfvd** [comment]
Thanks, added the suggestions to the app, will be available in the next release!
