### ISSUE TITLE
Countdown stopped triggers continues after upgrading to 2.1.0

### ISSUE THREAD

**Issue by wlauvenberg** [ralfvd/nl.bevlogenheid.countdown#37]
Previous behavior:
Flow was triggered once when the countdown stopped.

Current behavior (version 2.1.0):
When the countdown has a stopped state the flow is triggered, which is evaluated almost every second.

Diagnostic report:
385b73c9-3aae-4a43-8816-4daec904ea9f

**Comment by ralfvd** [comment]
I've just released 2.1.1 where this bug should be fixed.

Thanks for noticing!  Let me know if it works again in your situation.

**Comment by wlauvenberg** [comment]
Behavior is again as expected. Good job, thanks
