### ISSUE TITLE
It's not possible to add a new timer (v2.1.0)

### ISSUE THREAD

**Issue by dirkg173** [ralfvd/nl.bevlogenheid.countdown#38]
Installed the CountDown app today (v2.1.0) but it's not possible to add a timer. I restarted the app, but still not possible.

Homey Firmware: 7.4.1-rc.2

https://user-images.githubusercontent.com/40319629/166225815-b7e88121-39a8-49ab-b7ab-87efe9bd9b70.mp4

**Comment by ralfvd** [comment]
I've just released 2.1.1 where this error should be fixed. Thanks for noticing!

**Comment by dirkg173** [comment]
Thank you very much for the quick correction.
Now it works like it should.
