### ISSUE TITLE
[Enhancement] Pause Timer

### ISSUE THREAD

**Issue by Arjanvde** [ralfvd/nl.bevlogenheid.countdown#5]
Hi Ralf,

Is it possible to add the function that a timer is paused with a flow action and can be resumed by a different flow card.

Many thanks,
Arjan

**Comment by ralfvd** [comment]
I need to check if this is possible, as the current software just does a CountDown of all timers that are not zero. So pausing a single timer is not trivial.

**Comment by Arjanvde** [comment]
Hi Ralf,

With the introduction of global tags this issue is solved for me.  I now write the remaining time ta a  better logic variable and use this variable on a restart of the countdown timer.

Thanks
Arjan

**Comment by ralfvd** [comment]
Arjan,

Perfect, that was the idea of the global tags. A  bit of a workaround, but
it works (until I figure out another way to pause/resume timers).

Have fun!

Ralf
