### ISSUE TITLE
New version 1.0.7 crashes all the time when adding a new countdown

### ISSUE THREAD

**Issue by mruiter** [ralfvd/nl.bevlogenheid.countdown#6]
Stack trace:

ReferenceError: variable is not defined
at /lib/variablemanagement/variablemanagement.js:107:13
at Homey.client.emit (/manager/flow.js:1:1680)
at process.<anonymous> (/helpers/client.js:1:1215)
at emitTwo (events.js:126:13)
at process.emit (events.js:214:7)
at emit (internal/child_process.js:772:12)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)

Exit code: 1
Exit signal: null

I Cant create any new countdown timers anymore. When i punch add for the new counter i see it get added to the list. When i go away and back to the setting page its gone again. Also when its added and i puch in edit the app crashes . You should have had a report from my homey just now.

**Comment by ralfvd** [comment]
I see the same  behaviour here, so I'll have a look as soon as possible, this was something I didn't test.

**Comment by ralfvd** [comment]
1.1.0 is on Github right now, that should solve the problem , at least it did on my side ;-) 
Approval pending with Athom, but you can manually install if a quick fix is needed. Let me know how it works for you.  I'll do some more regression testing later today.

**Comment by mruiter** [comment]
Checked and confirmed working. I'll create another issue for a new bug i found.
Thx for youre fantastic work/app
