### ISSUE TITLE
Version 1.1.0 - Auto populate "pas zandlopen aan" not working

### ISSUE THREAD

**Issue by mruiter** [ralfvd/nl.bevlogenheid.countdown#7]
The flow card "pas zandloper aan" is giving a error on auto populating the list of zandlopers.

See screenshot

![img_1396](https://user-images.githubusercontent.com/17739535/32857805-6c3e3686-ca49-11e7-9bdd-c3a8863f4306.JPG)

**Comment by ralfvd** [comment]
Will be fixed in 1.1.1 ( pending approval but already available on GitHub)
