### ISSUE TITLE
Adjust countdown timer error message

### ISSUE THREAD

**Issue by cbho** [ralfvd/nl.bevlogenheid.countdown#8]
When using the flow card an error message "missing_listener" appears:
![image](https://user-images.githubusercontent.com/29979509/33288025-11836e34-d3bb-11e7-9119-7b2e0eb55aea.png)

CountDown variable choosen from drop down menu and running when flow is triggered.
Homey fw 1.5.5, CountDown 1.1.1.

**Comment by ralfvd** [comment]
Great catch. My bugfix in 1.1.1 wasn't that good, so it kept the adjust countdown timer broken. It is now fixed in 1.1.2 and pending approval in the app store. I'll close this ticket once it is approved.

Thanks for noticing and filing an issue, greatly appreciated!

**Comment by cbho** [comment]
Totally works now!
Thumbs up!
