### ISSUE TITLE
Changing a timer in settings when a timer is active, the input loses focus every second

### ISSUE THREAD

**Issue by WrDX** [ralfvd/nl.bevlogenheid.countdown#9]
If a timer is counting down and I want to edit any timer's value in the app settings, the input loses focus every second. This is quite annoying when testing.

I think this is due to the running timer(s) "time left" being updated, since the focus on the input is lost at that exact moment.

**Comment by ralfvd** [comment]
Hi, I can reproduce this error, but I haven't found an fix yet. It is indeed due to the fact that the values are being updated, and this causes the focus to be lost. 

I'll keep looking to find a way to work around this.

**Comment by robiebab** [comment]
i think i have found a solution:   http://inimino.org/~inimino/blog/javascript_live_text_input

**Comment by ralfvd** [comment]
@robiebab thanks for the suggestion, I'll have a look at that. At first sight, it seems this is the other way around; use the input of what is typed to update the page. The challenge with this request is that there is an update of the table from 'outside' the table itself. 
I think I have a solution -although not very elegant and there are some drawbacks- . I'll look further into it the coming days to see if there is a more elegant way to keep the focus.  And I'll also look at your suggestion, maybe it will give a good direction ! Thanks.

**Comment by WrDX** [comment]
I saw my Homey updated your app, I've tested it and it's fixed. Thank you!
